/* ex ok  SignaturePermutation  */
/* mma  SignaturePermutation[{1,2,3}] */
SignaturePermutation([1,2,3]);
1 ;
/* endex */

/* ex ok  SignaturePermutation  */
/* mma  SignaturePermutation[{2,1,3}] */
SignaturePermutation([2,1,3]);
- 1 ;
/* endex */

/* ex ok  SignaturePermutation  */
/* mma  SignaturePermutation[{3,2,1}] */
SignaturePermutation([3,2,1]);
- 1 ; 
/* endex */

/* ex ok  SignaturePermutation  */
/* mma  Apply["+",Map[SignaturePermutation,Permutations[Range[7]]]] */
Apply("+",Map(SignaturePermutation,Permutations(Range(7))));
0 ;
/* cm Compute all permutations of 1..7, Sum the signatures. */
/* cm There are equal numbers of even and odd permutations. */
/* cm This goes much faster if we do compile(SignaturePermutation). */
/* cm Careful: the example writing code stripped the "" from the +. */
/* endex */

