Product((i^2),[i,1,6]);


Product((i^2),[i,1,n]);


Product((1-((i^4)^-1)),[i,2,inf]);


Product((2^(j+i)),[i,1,p],[j,1,i]);


Product(f(i),[i,1,4]);


Product(f(i),[i,1,4,2]);


Product(f(i),[i,[a,b,c]]);


Product(f(i,j),[i,1,3],[j,1,3]);


Product(f(i,j),[i,1,3,2],[j,1,3,1/2]);


Product(f(i,j),[i,1,3],[j,1,i]);


Product(f(i,j),[i,[a,b,c]],[j,1,3]);


Product((1+((i^2)^-1)),[i,inf]);


Product((1+(((i^2)+1)^-1)),[i,(-1*inf),inf]);

